In [1]:
import numpy as np


In [23]:
#ejercicio 1
ventas = [18, 12, 25, 10, 8, 15,
20, 14, 22, 13, 11, 17,
16, 19, 27, 9, 12, 18,
24, 17, 21, 15, 10, 20]

ventas_matriz=np.array(ventas)
ventas_matriz=ventas_matriz.reshape(4,6)
print(ventas_matriz)

#2
print(ventas_matriz.dtype)
print(ventas_matriz.ndim)
print(ventas_matriz.shape)

#3
ventas_matriz_turno=ventas_matriz.sum(axis=1)
print(ventas_matriz_turno)
print("-"*20)

ventas_matriz_producto=ventas_matriz.sum(axis=0)
print(ventas_matriz_turno)
print("-"*20)
#4
print(ventas_matriz_turno.argmax())
print("-"*20)
#5
ventas_incremen=ventas_matriz.copy()
ventas_incremen+=2
print(ventas_matriz)
print(ventas_incremen)

[[18 12 25 10  8 15]
 [20 14 22 13 11 17]
 [16 19 27  9 12 18]
 [24 17 21 15 10 20]]
int64
2
(4, 6)
[ 88  97 101 107]
--------------------
[ 88  97 101 107]
--------------------
3
--------------------
[[18 12 25 10  8 15]
 [20 14 22 13 11 17]
 [16 19 27  9 12 18]
 [24 17 21 15 10 20]]
[[20 14 27 12 10 17]
 [22 16 24 15 13 19]
 [18 21 29 11 14 20]
 [26 19 23 17 12 22]]


np.int64(97)

In [30]:
# Ejercicio 2. Inventario después de las ventas
stock = np.array([
    [25, 18, 30, 12, 20],
    [14, 22, 16, 28, 19],
    [35, 17, 24, 15, 21]])

ventas = np.array([ 
    [10, 20, 12, 8, 7],
    [16, 10, 18, 9, 20],
    [15, 19, 8, 17, 11]])

#1
stock_restante=stock-ventas
print(stock_restante)
#2
mascara=stock_restante<0
print(stock_restante[mascara])


#3
stock_restante_corregido=stock_restante.copy()
stock_restante_corregido[mascara]=0
print(stock_restante_corregido)

#4
stock_restante_antes=stock_restante.sum(axis=1)
print(stock_restante_antes)

[[15 -2 18  4 13]
 [-2 12 -2 19 -1]
 [20 -2 16 -2 10]]
[-2 -2 -2 -1 -2 -2]
[[15  0 18  4 13]
 [ 0 12  0 19  0]
 [20  0 16  0 10]]
[48 26 42]


In [45]:
# Ejercicio 3. Facturación por sucursal
precios = np.array([
    [4.5, 6.0, 3.5, 8.0],
    [4.7, 5.8, 3.6, 8.2],
    [4.6, 6.1, 3.4, 7.9]])
unidades = np.array([
    [30, 18, 42, 15],
    [25, 20, 35, 17],
    [28, 22, 40, 14]])

total=precios*unidades
print(total)
print("-"*20)

#2
total_sucursal=total.sum(axis=1)
total_productos=total.sum(axis=0)
print(total_sucursal)
print(total_productos)
print("-"*20)

#3
print(total_sucursal.argmax())

#4
valor_max=total.max()
print(valor_max)

mascara=total
for fila in range(mascara.shape[0]):
    for columna in range(mascara.shape[1]):
        if valor_max==total[fila,columna]:
            print(fila,columna)

print(total.T)


[[135.  108.  147.  120. ]
 [117.5 116.  126.  139.4]
 [128.8 134.2 136.  110.6]]
--------------------
[510.  498.9 509.6]
[381.3 358.2 409.  370. ]
--------------------
0
147.0
0 2
[[135.  117.5 128.8]
 [108.  116.  134.2]
 [147.  126.  136. ]
 [120.  139.4 110.6]]


In [21]:
#4
notas = np.array(
    [
        [14, 16, 13, 15],
        [18, 17, 16, 19],
        [11, 13, 12, 14],
        [16, 15, 17, 16],
        [13, 10, 15, 12]
    ]
)

print(notas.shape)
puntaje_total=notas.sum(axis=1)
print(puntaje_total)

promedio= notas.mean(axis=1)
print(promedio)

promedio_sin_mean=puntaje_total/notas.shape[1]
print(promedio_sin_mean)
print("-"*15)

promedio_max=promedio.argmax()+1
print(promedio_max)

total_evaluacion=notas.sum(axis=0)
print(total_evaluacion)
menor_rendimiento=total_evaluacion.argmin()+1
print(menor_rendimiento)
print("-"*15)

mascara=notas>13
filtramayor13=notas[mascara]
print(filtramayor13)
print("-"*15)


(5, 4)
[58 70 50 64 50]
[14.5 17.5 12.5 16.  12.5]
[14.5 17.5 12.5 16.  12.5]
---------------
2
[72 71 73 76]
2
---------------
[14 16 15 18 17 16 19 14 16 15 17 16 15]
---------------
