In [1]:
import numpy as np
print(np.__version__)

2.5.1


In [2]:
vector_unos= np.ones(10, dtype='int64')
print(vector_unos)

[1 1 1 1 1 1 1 1 1 1]


In [3]:
matriz_unos= np.ones((3,3), dtype='int64')
print(matriz_unos)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
np.arange(0,10,3)


array([0, 3, 6, 9])

In [5]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [6]:
np.linspace(0,5,7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [7]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [11]:
matriz= np.full((2,5),8)
print(matriz)
print("-"*10)
matriz_Zeros_como=np.zeros_like(matriz)
print(matriz_Zeros_como)

[[8 8 8 8 8]
 [8 8 8 8 8]]
----------
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
np.full(5,1.4).astype(int)

array([1, 1, 1, 1, 1])

In [31]:
#ejercicio 1
array= np.arange(10,50,5)
print(array)
print("-"*10)
#EJERCIO 2
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.size)
print("-"*10)
#EJERCIO 3
matriz_zero=np.zeros((3,4))
identidad=np.eye(3)
print(matriz_zero)
print(identidad)
print("-"*10)

arr=np.linspace(-1,1,7)
print(arr)
print("-"*10)

array_flotante=array.astype('float32')
print(array_flotante.dtype)
print(array_flotante.itemsize)

[10 15 20 25 30 35 40 45]
----------
(8,)
1
int64
8
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------
[-1.         -0.66666667 -0.33333333  0.          0.33333333  0.66666667
  1.        ]
----------
float32
4


In [34]:
arr=np.arange(0,16,1)
matriz=arr.reshape((4,4))
print(matriz)
matriz[1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([4, 5, 6, 7])

In [35]:
matriz[1,1]

np.int64(5)

In [37]:
matriz[:,-1]

array([ 3,  7, 11, 15])

In [38]:
matriz[-1,-1]

np.int64(15)

In [ ]:
vector=np.arange(0,10,1)
vista= vector[6:].copy()
print(vector)
print(vista)

vista[-1]=1000
print(vista)

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[   6    7    8 1000]


In [48]:
a= np.array([1.0,4.0,9.0])
np.clip(a,2,5)

array([2., 4., 5.])

In [50]:
a= np.array([1.0,4.0,9.0, np.nan])
np.isnan(a).sum()

np.int64(1)

In [52]:
np.isclose(70,6,2)

np.False_

In [55]:
array=np.array([1,2,3,4])
array.min()

np.int64(1)

In [56]:
array.argmax()

np.int64(3)